language: go
go: 1.8.x
install:
- go get github.com/Masterminds/glide
- wget https://raw.githubusercontent.com/grpc-ecosystem/grpc-gateway/master/.travis/install-protoc.sh && chmod +x install-protoc.sh && ./install-protoc.sh 3.2.0
- go get -u github.com/golang/protobuf/protoc-gen-go
script:
- make install
- make test
cache:
  directories:
  - $HOME/local
env:
  global:
  - "PATH=$PATH:$HOME/local/bin"