// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gotemplate.proto

package gotemplate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GoTemplateOption struct {
	Enable               bool     `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoTemplateOption) Reset()         { *m = GoTemplateOption{} }
func (m *GoTemplateOption) String() string { return proto.CompactTextString(m) }
func (*GoTemplateOption) ProtoMessage()    {}
func (*GoTemplateOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e0d1d51a018095f, []int{0}
}

func (m *GoTemplateOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoTemplateOption.Unmarshal(m, b)
}
func (m *GoTemplateOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoTemplateOption.Marshal(b, m, deterministic)
}
func (m *GoTemplateOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoTemplateOption.Merge(m, src)
}
func (m *GoTemplateOption) XXX_Size() int {
	return xxx_messageInfo_GoTemplateOption.Size(m)
}
func (m *GoTemplateOption) XXX_DiscardUnknown() {
	xxx_messageInfo_GoTemplateOption.DiscardUnknown(m)
}

var xxx_messageInfo_GoTemplateOption proto.InternalMessageInfo

func (m *GoTemplateOption) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

var E_GoTemplateOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*GoTemplateOption)(nil),
	Field:         65020,
	Name:          "gotemplate.go_template_option",
	Tag:           "bytes,65020,opt,name=go_template_option",
	Filename:      "gotemplate.proto",
}

func init() {
	proto.RegisterType((*GoTemplateOption)(nil), "gotemplate.GoTemplateOption")
	proto.RegisterExtension(E_GoTemplateOption)
}

func init() { proto.RegisterFile("gotemplate.proto", fileDescriptor_9e0d1d51a018095f) }

var fileDescriptor_9e0d1d51a018095f = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xcf, 0x2f, 0x49,
	0xcd, 0x2d, 0xc8, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x48, 0x29, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0x65, 0x92, 0x4a, 0xd3, 0xf4, 0x53,
	0x52, 0x8b, 0x93, 0x8b, 0x32, 0x0b, 0x4a, 0xf2, 0x8b, 0x20, 0xaa, 0x95, 0xb4, 0xb8, 0x04, 0xdc,
	0xf3, 0x43, 0xa0, 0xea, 0xfd, 0x0b, 0x4a, 0x32, 0xf3, 0xf3, 0x84, 0xc4, 0xb8, 0xd8, 0x52, 0xf3,
	0x12, 0x93, 0x72, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x82, 0xa0, 0x3c, 0xab, 0x5c, 0x2e,
	0xa1, 0xf4, 0xfc, 0x78, 0x98, 0xe1, 0xf1, 0xf9, 0x10, 0xd5, 0xf2, 0x7a, 0x10, 0x4b, 0xf4, 0x60,
	0x96, 0xe8, 0xf9, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0x43, 0x4d, 0x2b, 0x96, 0xf8, 0xf3, 0x9b, 0x59,
	0x81, 0x51, 0x83, 0xdb, 0x48, 0x46, 0x0f, 0xc9, 0xad, 0xe8, 0x96, 0x06, 0x09, 0xa4, 0xa3, 0x89,
	0x38, 0xf1, 0x44, 0x21, 0x79, 0x25, 0x89, 0x0d, 0x6c, 0xbc, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xcf, 0xae, 0x30, 0x73, 0xf1, 0x00, 0x00, 0x00,
}
